#!/bin/sh

#    ______   ______   ______  __     __   __    __   ______   ______   
#   /\  == \ /\  ___\ /\  == \/\ \  _ \ \ /\ "-./  \ /\  == \ /\  ___\  
#   \ \  __< \ \___  \\ \  _-/\ \ \/ ".\ \\ \ \-./\ \\ \  __< \ \ \____ 
#    \ \_____\\/\_____\\ \_\   \ \__/".~\_\\ \_\ \ \_\\ \_\ \_\\ \_____\
#     \/_____/ \/_____/ \/_/    \/_/   \/_/ \/_/  \/_/ \/_/ /_/ \/_____/
#                                                                       

# initialize workspaces
bspc monitor -d 1 2 3 4 5

# window rendering settings
bspc config border_width           2
bspc config focused_border_color   "#ededeb"
bspc config normal_border_color    "#282c34"
bspc config split_ratio            0.5
bspc config window_gap             8

# monocle layout
bspc config borderless_monocle     true
bspc config gapless_monocle        true

# move and resize windows with cursor
bspc config focus_follows_pointer  true
bspc config pointer_action1        move
bspc config pointer_action2        resize_side
bspc config pointer_action3        resize_corner
bspc config pointer_modifier       mod4

# display applications in correct workspaces
bspc rule -a Brave-browser center=on desktop=5 follow=on rectangle=1500x900+0+0 state=floating
bspc rule -a Firefox desktop=2 focus=on follow=on state=fullscreen
bspc rule -a TelegramDesktop desktop=3 state=fullscreen
bspc rule -a kdenlive desktop=1 state=fullscreen follow=on
bspc rule -a pcsx2-qt desktop=5 state=fullscreen follow=on
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a copyq state=floating

# external rules for complex window names
bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/external_rules"

# autostart programs
"$XDG_CONFIG_HOME/bspwm/autostart" &
